"""view/php-standalone generator.

Takes a :class:`ViewBundle` and emits a single-file PHP aggregator:

- ``index.php`` — one file that fetches all configured sources server-side,
  renders an HTML shell, and exposes ``?format=json`` for client-side polling.
- ``README.md`` — how to run (``php -S 0.0.0.0:$PORT index.php``).

Design choices:

- No PHP framework, no Composer. A freshly-installed PHP 8 is the only
  prerequisite. This is the deliberate point of this target.
- Polling is the default transport. The client re-hits ``?format=json``
  at the minimum refresh interval across all sources. SSE and static variants
  are separate generators (not implemented here).
- No custom Jinja/Twig template engine in the MVP. A ``template.source`` on
  the bundle is emitted as a README note; the default card layout is used.
  (This keeps the generator pure and avoids template-injection footguns.)
"""

from __future__ import annotations

from typing import Any

from ...ir import AnyBundle, ViewBundle
from ._shared import refresh_to_ms as _refresh_to_ms


def _php_quote(value: str) -> str:
    """Produce a PHP single-quoted string literal from a Python string."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _php_array(data: Any, indent: int = 0) -> str:
    """Render a Python value as a PHP array literal (pretty-printed)."""
    pad = "    " * indent
    pad_inner = "    " * (indent + 1)
    if isinstance(data, dict):
        if not data:
            return "[]"
        parts = ["["]
        for k, v in data.items():
            parts.append(
                f"{pad_inner}{_php_quote(str(k))} => {_php_array(v, indent + 1)},"
            )
        parts.append(pad + "]")
        return "\n".join(parts)
    if isinstance(data, list):
        if not data:
            return "[]"
        parts = ["["]
        for v in data:
            parts.append(f"{pad_inner}{_php_array(v, indent + 1)},")
        parts.append(pad + "]")
        return "\n".join(parts)
    if isinstance(data, bool):
        return "true" if data else "false"
    if isinstance(data, (int, float)):
        return str(data)
    if data is None:
        return "null"
    return _php_quote(str(data))


def _sources_php_literal(bundle: ViewBundle) -> str:
    """Emit the $SOURCES associative PHP array."""
    data = {
        s.name: {
            "uri": s.uri,
            "method": s.method,
            "headers": s.headers,
            "refresh_ms": _refresh_to_ms(s.refresh),
            "depends_on": list(s.depends_on),
        }
        for s in bundle.sources
    }
    return _php_array(data)


class PhpStandaloneViewGenerator:
    target = "view/php-standalone"
    category = "view"

    def generate(self, bundle: AnyBundle) -> dict[str, str]:
        if not isinstance(bundle, ViewBundle):
            raise TypeError(
                f"{self.target} expects a ViewBundle, got {type(bundle).__name__}"
            )
        return {
            "index.php": self._index_php(bundle),
            "README.md": self._readme(bundle),
        }

    # ----- file bodies -------------------------------------------------------

    def _index_php(self, bundle: ViewBundle) -> str:
        sources_literal = _sources_php_literal(bundle)
        min_refresh_ms = min(
            (_refresh_to_ms(s.refresh) for s in bundle.sources), default=5000
        )
        header_lines = [
            "<?php",
            f"// Auto-generated by Service Factory - {self.target}",
            f"// Bundle: {bundle.name} v{bundle.version}",
            f"// Hash:   {bundle.contract_hash()}",
            "// Do not edit; regenerate from the bundle JSON.",
            "",
            f"$BUNDLE_NAME = {_php_quote(bundle.name)};",
            f"$BUNDLE_VERSION = {_php_quote(bundle.version)};",
            f"$BUNDLE_DESCRIPTION = {_php_quote(bundle.description)};",
            f"$TRANSPORT = {_php_quote(bundle.transport)};",
            f"$MIN_REFRESH_MS = {min_refresh_ms};",
            f"$SOURCES = {sources_literal};",
            "",
        ]
        return "\n".join(header_lines) + _PHP_RUNTIME

    def _readme(self, bundle: ViewBundle) -> str:
        port = bundle.exposure.port
        source_list = "\n".join(
            f"- **{s.name}** — `{s.method} {s.uri}` (refresh: {s.refresh})"
            for s in bundle.sources
        )
        min_refresh = min(_refresh_to_ms(s.refresh) for s in bundle.sources)
        tmpl_note = ""
        if bundle.template.source or bundle.template.source_uri:
            tmpl_note = (
                "\n> Note: this bundle declares a custom template, but the\n"
                "> `view/php-standalone` generator currently ignores it and\n"
                "> uses the default card layout. Custom templates will be\n"
                "> honoured by a future Jinja/Twig-aware generator.\n"
            )
        lines = [
            f"# {bundle.name}",
            "",
            bundle.description or "Auto-generated aggregation view.",
            "",
            "Generated by the **view/php-standalone** target of Service Factory.",
            f"Bundle hash: `{bundle.contract_hash()}`.",
            "",
            "## Run",
            "",
            "```bash",
            f"php -S 0.0.0.0:{port} index.php",
            "```",
            "",
            f"Then open <http://localhost:{port}/>. The client polls",
            f"`?format=json` every {min_refresh}ms and rebuilds the page without a full reload.",
            "",
            "## Sources",
            "",
            source_list,
            "",
            "## Endpoints",
            "",
            "- `GET /`               — HTML page with embedded polling client.",
            "- `GET /?format=json`   — fresh aggregate of every source as JSON.",
            '- `GET /health`         — liveness probe returning `{ "status": "ok" }`.',
            tmpl_note.rstrip() if tmpl_note else "",
            "## Notes",
            "",
            "- No composer, no framework. PHP 8.0+ is the only requirement.",
            "- CORS is *not* handled here; each upstream service must allow this",
            "  origin if the view is served from a different host/port.",
            "- The generated file is side-effect free at import time; it only",
            "  does work when handling an HTTP request.",
            "",
        ]
        return "\n".join(lines)


# Runtime fragment appended verbatim to the generated index.php.  Placed
# at module scope so it is not re-indented on every call.
_PHP_RUNTIME = r"""
// ---------------------------------------------------------------------------
// Runtime
// ---------------------------------------------------------------------------

function build_headers(array $h): string {
    $out = [];
    foreach ($h as $k => $v) {
        $out[] = $k . ': ' . $v;
    }
    return implode("\r\n", $out);
}

function fetch_source(array $src): array {
    $opts = [
        'http' => [
            'method' => $src['method'] ?? 'GET',
            'header' => build_headers($src['headers'] ?? []),
            'timeout' => 10,
            'ignore_errors' => true,
        ],
    ];
    $ctx = stream_context_create($opts);
    $raw = @file_get_contents($src['uri'], false, $ctx);
    if ($raw === false) {
        return ['ok' => false, 'error' => 'fetch failed', 'uri' => $src['uri']];
    }
    $decoded = json_decode($raw, true);
    if (json_last_error() === JSON_ERROR_NONE) {
        return ['ok' => true, 'data' => $decoded, 'raw' => null];
    }
    return ['ok' => true, 'data' => null, 'raw' => $raw];
}

function aggregate_all(array $sources): array {
    $out = [];
    foreach ($sources as $name => $cfg) {
        $out[$name] = fetch_source($cfg);
    }
    return [
        'timestamp' => date(DATE_ATOM),
        'sources' => $out,
    ];
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$query = [];
parse_str((string)(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_QUERY) ?? ''), $query);

if ($path === '/health') {
    header('Content-Type: application/json');
    echo json_encode([
        'status' => 'ok',
        'service' => $BUNDLE_NAME,
        'version' => $BUNDLE_VERSION,
    ]);
    exit;
}

if (($query['format'] ?? '') === 'json') {
    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode(aggregate_all($SOURCES));
    exit;
}

// ---------------------------------------------------------------------------
// Full HTML render
// ---------------------------------------------------------------------------

$data = aggregate_all($SOURCES);
header('Content-Type: text/html; charset=utf-8');
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><?= htmlspecialchars($BUNDLE_NAME) ?></title>
<style>
  :root { color-scheme: light dark; }
  body { font: 14px/1.4 system-ui, sans-serif; margin: 0; padding: 1rem 1.25rem; }
  header { border-bottom: 1px solid #8884; padding-bottom: .5rem; margin-bottom: 1rem; }
  h1 { margin: 0; font-size: 1.25rem; }
  h2 { margin: 0 0 .25rem; font-size: 1rem; }
  small { color: #888; }
  main { display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(360px, 1fr)); }
  section.source { border: 1px solid #8884; border-radius: 6px; padding: .75rem; }
  section.source.error { border-color: #d33; }
  pre { margin: 0; white-space: pre-wrap; word-break: break-word; max-height: 24rem; overflow: auto; background: #8881; padding: .5rem; border-radius: 4px; }
</style>
</head>
<body>
<header>
  <h1><?= htmlspecialchars($BUNDLE_NAME) ?> <small>v<?= htmlspecialchars($BUNDLE_VERSION) ?></small></h1>
  <?php if ($BUNDLE_DESCRIPTION !== ''): ?><p><?= htmlspecialchars($BUNDLE_DESCRIPTION) ?></p><?php endif; ?>
  <small>updated <span id="ts"><?= htmlspecialchars($data['timestamp']) ?></span> — transport: <?= htmlspecialchars($TRANSPORT) ?></small>
</header>
<main id="content">
<?php foreach ($data['sources'] as $name => $result): ?>
  <section class="source<?= $result['ok'] ? '' : ' error' ?>" data-name="<?= htmlspecialchars((string)$name) ?>">
    <h2><?= htmlspecialchars((string)$name) ?></h2>
    <?php if (!$result['ok']): ?>
      <pre>ERROR: <?= htmlspecialchars((string)($result['error'] ?? 'unknown')) ?></pre>
    <?php else: ?>
      <pre><?= htmlspecialchars(json_encode($result['data'] ?? $result['raw'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) ?></pre>
    <?php endif; ?>
  </section>
<?php endforeach; ?>
</main>
<script>
(function(){
  const refreshMs = <?= (int)$MIN_REFRESH_MS ?>;
  if (refreshMs <= 0) return;
  const contentEl = document.getElementById('content');
  const tsEl = document.getElementById('ts');
  function esc(s){ return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function renderSource(name, result){
    const body = result.ok
      ? esc(JSON.stringify(result.data ?? result.raw, null, 2))
      : 'ERROR: ' + esc(result.error || 'unknown');
    const cls = 'source' + (result.ok ? '' : ' error');
    return '<section class="' + cls + '" data-name="' + esc(name) + '">' +
             '<h2>' + esc(name) + '</h2>' +
             '<pre>' + body + '</pre>' +
           '</section>';
  }
  async function tick(){
    try {
      const resp = await fetch('?format=json', {cache: 'no-store'});
      if (!resp.ok) return;
      const payload = await resp.json();
      tsEl.textContent = payload.timestamp;
      contentEl.innerHTML = Object.entries(payload.sources).map(([n, r]) => renderSource(n, r)).join('');
    } catch(e) { /* swallow, retry next tick */ }
  }
  setInterval(tick, refreshMs);
})();
</script>
</body>
</html>
"""
