"""view/static-html generator.

Takes a :class:`ViewBundle` and emits a single zero-dependency HTML file:

- ``index.html`` — self-contained page. Every source is fetched from the
  browser at its own refresh interval; aggregation happens client-side.
- ``README.md`` — how to serve the file and the CORS caveat that comes with
  the fully-client-side design.

Design choices:

- Per-source refresh. Each source keeps its own ``setInterval`` so a fast
  "devices" feed (1s) does not force a slow "health" feed (5s) to re-poll.
- ``refresh: "never"`` means "fetch exactly once on load".
- ``depends_on`` delays a source's first fetch until each listed dependency
  has completed at least one successful fetch. The chain is flat — no
  topological sort, no cycle detection; cycles self-resolve as "everyone
  waits forever", which is loud and easy to spot.
- Custom headers / methods from ``Source`` translate 1:1 into ``fetch`` options.
- No framework, no build step. Just an HTML file you can ``file://`` open
  (modulo CORS) or serve with any static file server.
"""
from __future__ import annotations

import json
from html import escape
from typing import Any

from ...ir import AnyBundle, Source, ViewBundle
from ._shared import is_never, refresh_to_ms


def _source_to_js(src: Source) -> dict[str, Any]:
    """Render a :class:`Source` as a plain JSON-serialisable dict for the
    in-page ``SOURCES`` literal. Kept trivial — one branch per field."""
    return {
        "name": src.name,
        "uri": src.uri,
        "method": src.method or "GET",
        "headers": dict(src.headers),
        "refreshMs": refresh_to_ms(src.refresh),
        "once": is_never(src.refresh),
        "dependsOn": list(src.depends_on),
    }


class StaticHtmlViewGenerator:
    target = "view/static-html"
    category = "view"

    def generate(self, bundle: AnyBundle) -> dict[str, str]:
        if not isinstance(bundle, ViewBundle):
            raise TypeError(
                f"{self.target} expects a ViewBundle, got {type(bundle).__name__}"
            )
        return {
            "index.html": self._index_html(bundle),
            "README.md": self._readme(bundle),
        }

    # ----- file bodies -------------------------------------------------------

    def _index_html(self, bundle: ViewBundle) -> str:
        sources_js = json.dumps(
            [_source_to_js(s) for s in bundle.sources],
            indent=2,
        )
        initial_cards = "\n".join(
            f'      <section class="source" data-name="{escape(s.name)}">'
            f'<h2>{escape(s.name)}</h2><pre>loading…</pre></section>'
            for s in bundle.sources
        )
        return _HTML_TEMPLATE.format(
            name=escape(bundle.name),
            version=escape(bundle.version),
            description=escape(bundle.description),
            transport=escape(bundle.transport),
            hash=bundle.contract_hash(),
            target=self.target,
            initial_cards=initial_cards,
            sources_js=sources_js,
        )

    def _readme(self, bundle: ViewBundle) -> str:
        port = bundle.exposure.port
        source_list = "\n".join(
            f"- **{s.name}** — `{s.method} {s.uri}` (refresh: {s.refresh})"
            for s in bundle.sources
        )
        lines = [
            f"# {bundle.name}",
            "",
            bundle.description or "Auto-generated aggregation view.",
            "",
            "Generated by the **view/static-html** target of Service Factory.",
            f"Bundle hash: `{bundle.contract_hash()}`.",
            "",
            "## Serve",
            "",
            "Any static file server works. Three ergonomic options:",
            "",
            "```bash",
            f"python3 -m http.server {port}",
            f"# or:  caddy file-server --listen :{port}",
            f"# or:  npx --yes serve -l {port} .",
            "```",
            "",
            f"Then open <http://localhost:{port}/index.html>.",
            "",
            "## Sources",
            "",
            source_list,
            "",
            "## CORS",
            "",
            "Because every source is fetched **by the browser**, each upstream",
            "service must allow this origin via `Access-Control-Allow-Origin`.",
            "If you cannot change the upstream, use the `view/php-standalone`",
            "target instead — it aggregates server-side and sidesteps CORS.",
            "",
            "## Opening via `file://`",
            "",
            "Modern browsers block `fetch()` from `file://` pages for cross-origin",
            "requests. Always serve the file over HTTP.",
            "",
        ]
        return "\n".join(lines)


# Single HTML template with double-braced placeholders for JavaScript blocks
# so that ``str.format`` does not misinterpret the JS object literals. Named
# fields we do want to substitute: ``{name}``, ``{version}``, ``{description}``,
# ``{transport}``, ``{hash}``, ``{target}``, ``{initial_cards}``, ``{sources_js}``.
_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{name}</title>
<meta name="generator" content="service-factory {target}">
<meta name="bundle-hash" content="{hash}">
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 14px/1.4 system-ui, sans-serif; margin: 0; padding: 1rem 1.25rem; }}
  header {{ border-bottom: 1px solid #8884; padding-bottom: .5rem; margin-bottom: 1rem; }}
  h1 {{ margin: 0; font-size: 1.25rem; }}
  h2 {{ margin: 0 0 .25rem; font-size: 1rem; display: flex; justify-content: space-between; gap: .5rem; align-items: baseline; }}
  h2 .meta {{ font: 11px/1 monospace; color: #888; font-weight: normal; }}
  small {{ color: #888; }}
  main {{ display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(360px, 1fr)); }}
  section.source {{ border: 1px solid #8884; border-radius: 6px; padding: .75rem; }}
  section.source.error {{ border-color: #d33; }}
  section.source.loading {{ opacity: .6; }}
  pre {{ margin: 0; white-space: pre-wrap; word-break: break-word; max-height: 24rem; overflow: auto; background: #8881; padding: .5rem; border-radius: 4px; }}
</style>
</head>
<body>
<header>
  <h1>{name} <small>v{version}</small></h1>
  <p>{description}</p>
  <small>transport: {transport} — hash: <code>{hash}</code></small>
</header>
<main id="content">
{initial_cards}
</main>
<script>
const SOURCES = {sources_js};

const bySelector = new Map(SOURCES.map(s => [s.name, document.querySelector('section.source[data-name="' + CSS.escape(s.name) + '"]')]));
const completedOnce = new Set();
const seenData = new Map();

function esc(s) {{
  return String(s).replace(/[&<>"']/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
}}

function renderSuccess(section, name, payload, updatedAt) {{
  const body = typeof payload === 'string'
    ? esc(payload)
    : esc(JSON.stringify(payload, null, 2));
  section.classList.remove('error', 'loading');
  section.innerHTML =
    '<h2>' + esc(name) + '<span class="meta">' + updatedAt.toISOString() + '</span></h2>' +
    '<pre>' + body + '</pre>';
}}

function renderError(section, name, err) {{
  section.classList.add('error');
  section.classList.remove('loading');
  section.innerHTML =
    '<h2>' + esc(name) + '<span class="meta">error</span></h2>' +
    '<pre>' + esc(String(err)) + '</pre>';
}}

async function fetchOnce(src) {{
  const section = bySelector.get(src.name);
  if (!section) return;
  try {{
    const resp = await fetch(src.uri, {{
      method: src.method,
      headers: src.headers,
      cache: 'no-store',
    }});
    if (!resp.ok) throw new Error('HTTP ' + resp.status);
    const ct = resp.headers.get('content-type') || '';
    const payload = ct.includes('application/json')
      ? await resp.json()
      : await resp.text();
    renderSuccess(section, src.name, payload, new Date());
    seenData.set(src.name, payload);
    completedOnce.add(src.name);
  }} catch (err) {{
    renderError(section, src.name, err);
  }}
}}

function depsReady(src) {{
  return src.dependsOn.every(d => completedOnce.has(d));
}}

async function runSource(src) {{
  // Wait for dependencies (poll every 100ms, bounded by caller via setInterval).
  if (!depsReady(src)) {{
    await new Promise(resolve => {{
      const iv = setInterval(() => {{
        if (depsReady(src)) {{ clearInterval(iv); resolve(undefined); }}
      }}, 100);
    }});
  }}
  await fetchOnce(src);
  if (src.once || src.refreshMs <= 0) return;
  setInterval(() => fetchOnce(src), src.refreshMs);
}}

for (const src of SOURCES) {{
  runSource(src);
}}
</script>
</body>
</html>
"""
