flowchart LR
    subgraph api__agent
        api__agent__execute_agent["execute_agent"]
    end
    subgraph api__auth
        api__auth__get_jwt_manager["get_jwt_manager"]
        api__auth__authenticate["authenticate"]
    end
    subgraph api__commands
        api__commands__pipeline__PipelineCommand__execute["execute"]
        api__commands__converttobase64__ConvertToBase64Command__execute["execute"]
        api__commands__get_registry["get_registry"]
        api__commands__pipeline___substitute["_substitute"]
        api__commands__fetch__FetchCommand__execute["execute"]
        api__commands__register_default_commands["register_default_commands"]
        api__commands__pipeline___to_data_uri["_to_data_uri"]
    end
    subgraph api__main
        api__main__issue_token["issue_token"]
        api__main__execute_query_get["execute_query_get"]
        api__main__run_agent["run_agent"]
        api__main__execute_query["execute_query"]
        api__main__execute_command["execute_command"]
    end
    subgraph api__policy
        api__policy__get_engine["get_engine"]
    end
    subgraph api__protocols
        api__protocols__get_registry["get_registry"]
        api__protocols__register_default_protocols["register_default_protocols"]
    end
    subgraph api__queries
        api__queries__QueryRegistry__list["list"]
        api__queries__from_url__FromUrlQuery__execute["execute"]
        api__queries__get_registry["get_registry"]
        api__queries__register_default_queries["register_default_queries"]
    end
    subgraph api__validators
        api__validators__validate_against_schema_uri["validate_against_schema_uri"]
    end
    subgraph cqrs_backend_workflows__server
        cqrs_backend_workflows__server__create_workflow["create_workflow"]
        cqrs_backend_workflows__server__validate_workflow["validate_workflow"]
        cqrs_backend_workflows__server__list_workflows["list_workflows"]
        cqrs_backend_workflows__server__update_workflow["update_workflow"]
    end
    subgraph cqrs_workflow_editor__src
        cqrs_workflow_editor__src__App__blob["blob"]
        cqrs_workflow_editor__src__App__onUploadWorkflow["onUploadWorkflow"]
        cqrs_workflow_editor__src__App__file["file"]
        cqrs_workflow_editor__src__App__workflow["workflow"]
        cqrs_workflow_editor__src__App__sizeKB["sizeKB"]
        cqrs_workflow_editor__src__App__reader["reader"]
        cqrs_workflow_editor__src__App__json["json"]
        cqrs_workflow_editor__src__App__mime["mime"]
        cqrs_workflow_editor__src__App__timer["timer"]
        cqrs_workflow_editor__src__App__mapToEdges["mapToEdges"]
        cqrs_workflow_editor__src__App__exportWorkflow["exportWorkflow"]
        cqrs_workflow_editor__src__App__onDownloadWorkflow["onDownloadWorkflow"]
        cqrs_workflow_editor__src__App__loadPredefinedWorkflow["loadPredefinedWorkflow"]
        cqrs_workflow_editor__src__App__fetchPreview["fetchPreview"]
        cqrs_workflow_editor__src__App__text["text"]
        cqrs_workflow_editor__src__App__mapToNodes["mapToNodes"]
    end
    subgraph frontend__html
        frontend__html__js__app__decodeB64["decodeB64"]
        frontend__html__js__app__renderDecoded["renderDecoded"]
        frontend__html__js__api__setToken["setToken"]
        frontend__html__js__api__request["request"]
        frontend__html__js__api__catalog["catalog"]
        frontend__html__js__api__runQuery["runQuery"]
        frontend__html__js__api__API["API"]
        frontend__html__js__api__setRole["setRole"]
        frontend__html__js__api__runCommand["runCommand"]
        frontend__html__js__api__login["login"]
        frontend__html__js__api__data["data"]
        frontend__html__js__api__getToken["getToken"]
    end
    frontend__html__js__api__API --> frontend__html__js__api__getToken
    frontend__html__js__api__request --> frontend__html__js__api__getToken
    frontend__html__js__api__login --> frontend__html__js__api__request
    frontend__html__js__api__login --> frontend__html__js__api__setToken
    frontend__html__js__api__login --> frontend__html__js__api__setRole
    frontend__html__js__api__data --> frontend__html__js__api__request
    frontend__html__js__api__catalog --> frontend__html__js__api__request
    frontend__html__js__api__runCommand --> frontend__html__js__api__request
    frontend__html__js__api__runQuery --> frontend__html__js__api__request
    frontend__html__js__app__renderDecoded --> frontend__html__js__app__decodeB64
    cqrs_workflow_editor__src__App__loadPredefinedWorkflow --> cqrs_workflow_editor__src__App__mapToNodes
    cqrs_workflow_editor__src__App__loadPredefinedWorkflow --> cqrs_workflow_editor__src__App__mapToEdges
    cqrs_workflow_editor__src__App__fetchPreview --> cqrs_workflow_editor__src__App__blob
    cqrs_workflow_editor__src__App__fetchPreview --> cqrs_workflow_editor__src__App__text
    cqrs_workflow_editor__src__App__sizeKB --> cqrs_workflow_editor__src__App__text
    cqrs_workflow_editor__src__App__mime --> cqrs_workflow_editor__src__App__text
    cqrs_workflow_editor__src__App__timer --> cqrs_workflow_editor__src__App__fetchPreview
    cqrs_workflow_editor__src__App__onDownloadWorkflow --> cqrs_workflow_editor__src__App__exportWorkflow
    cqrs_workflow_editor__src__App__workflow --> cqrs_workflow_editor__src__App__json
    cqrs_workflow_editor__src__App__onUploadWorkflow --> cqrs_workflow_editor__src__App__mapToNodes
    cqrs_workflow_editor__src__App__onUploadWorkflow --> cqrs_workflow_editor__src__App__mapToEdges
    cqrs_workflow_editor__src__App__file --> cqrs_workflow_editor__src__App__mapToNodes
    cqrs_workflow_editor__src__App__file --> cqrs_workflow_editor__src__App__mapToEdges
    cqrs_workflow_editor__src__App__reader --> cqrs_workflow_editor__src__App__mapToNodes
    cqrs_workflow_editor__src__App__reader --> cqrs_workflow_editor__src__App__mapToEdges
    api__commands__converttobase64__ConvertToBase64Command__execute --> api__queries__get_registry
    api__commands__fetch__FetchCommand__execute --> api__queries__get_registry
    api__main__issue_token --> api__auth__authenticate
    api__main__issue_token --> api__auth__get_jwt_manager
    api__main__execute_command --> api__policy__get_engine
    api__main__execute_query --> api__policy__get_engine
    api__main__execute_query_get --> api__main__execute_query
    api__main__run_agent --> api__agent__execute_agent
    api__main__run_agent --> api__policy__get_engine
    api__queries__from_url__FromUrlQuery__execute --> api__queries__get_registry
    api__queries__register_default_queries --> api__queries__get_registry
    api__commands__register_default_commands --> api__commands__get_registry
    api__commands__pipeline___substitute --> api__commands__pipeline___to_data_uri
    api__commands__pipeline__PipelineCommand__execute --> api__commands__pipeline___substitute
    api__validators__validate_against_schema_uri --> api__queries__QueryRegistry__list
    api__protocols__register_default_protocols --> api__protocols__get_registry
    cqrs_backend_workflows__server__list_workflows --> api__queries__QueryRegistry__list
    cqrs_backend_workflows__server__create_workflow --> cqrs_backend_workflows__server__validate_workflow
    cqrs_backend_workflows__server__update_workflow --> cqrs_backend_workflows__server__validate_workflow
