flowchart TD
    api__SUMD["api.SUMD<br/>42 funcs"]
    api__commands["api.commands<br/>18 funcs"]
    api__main["api.main<br/>15 funcs"]
    api__queries["api.queries<br/>9 funcs"]
    api__validators["api.validators<br/>2 funcs"]
    cqrs_backend_workflows__server["cqrs-backend-workflows.server<br/>18 funcs"]
    service_factory__factory["service-factory.factory<br/>58 funcs"]
    api__commands ==>|10| service_factory__factory
    api__main ==>|6| api__SUMD
    api__commands -->|3| api__SUMD
    api__validators -->|2| service_factory__factory
    cqrs_backend_workflows__server -->|1| service_factory__factory
    api__queries -->|1| service_factory__factory
