flowchart TD
    api__SUMD["api.SUMD<br/>37 funcs"]
    api__commands["api.commands<br/>18 funcs"]
    api__main["api.main<br/>15 funcs"]
    api__queries["api.queries<br/>9 funcs"]
    api__validators["api.validators<br/>2 funcs"]
    cqrs_backend_workflows__server["cqrs-backend-workflows.server<br/>18 funcs"]
    api__commands ==>|9| api__SUMD
    api__main ==>|6| api__SUMD
    cqrs_backend_workflows__server -->|1| api__commands
    api__validators -->|1| api__commands
    api__validators -->|1| api__SUMD
    api__queries -->|1| api__SUMD
